animal_community/accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static  


app_name = 'accounts'

urlpatterns = [
    path('',views.home, name='home'),
    path('regist', views.regist, name='regist'),
    path('activate_user/<uuid:token>',views.activate_user, name='activate_user'),
    path('user_login', views.user_login, name='user_login'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('user_edit', views.user_edit, name='user_edit'),
    path('user_profile/<int:user_id>', views.user_profile, name='user_profile'),
    path('change_password', views.change_password, name='change_password'),
    path('pet_regist/', views.pet_regist, name='pet_regist'),
    path('profile/pet/<int:pet_id>/', views.pet_profile, name='pet_profile'),
    path('delete_pet/<int:pet_id>', views.delete_pet, name='delete_pet'),
    path('pets/<int:pet_id>/edit/', views.pet_edit, name='pet_edit'),  # ペット編集へのリンク
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

animal_community/animal_community/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import show_error_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('chat_category/', include('chat_category.urls')),
]

handler404 = show_error_page

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

animal_community/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser, PermissionsMixin
)
from django.db.models.signals import post_save
from django.dispatch import receiver
from uuid import uuid4
from datetime import datetime, timedelta
from django.contrib.auth.models import UserManager
from django.contrib.auth.models import User
from django.conf import settings

class Pet(models.Model):
    name = models.CharField(max_length=100)
    age = models.PositiveIntegerField(null=True, blank=True)
    sex = models.CharField(max_length=10, choices=(('1', 'オス'), ('2', 'メス')), default=1)
    picture = models.ImageField(upload_to='pet_pictures/', blank=True, null=True)
    genre = models.CharField(
    max_length=10,
    choices=(('1', '犬'), ('2', '猫'), ('3', '鳥類'), ('4', '齧歯類'), ('5', '爬虫類')),
    default='1',
)
    breed = models.CharField(max_length=100, blank=True)  # 品種
    characteristic = models.TextField(blank=True)  # 性格や特徴
    owner = models.ForeignKey(
        'Users', on_delete=models.CASCADE, related_name='pets'
    )  # 所有者の追加

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.owner and hasattr(self, 'request'):
            # 保存時にリクエストが存在する場合、リクエストのユーザーを所有者として設定
            self.owner = self.request.user
        super().save(*args, **kwargs)
        
class Users(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=255)
    age = models.PositiveIntegerField()
    bio = models.TextField(max_length=500, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    picture = models.ImageField(upload_to='picture/', blank=True, null=True)
    favorite_animals = models.CharField(max_length=255, blank=True)  # 好きな動物のためのフィールド
    pet = models.ManyToManyField(Pet, blank=True, related_name='users') #飼っているペットのためのフィールド
    
    objects = UserManager()
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    
    class Meta:
        db_table = 'users'
        
class UserActivateTokensManager(models.Manager):
    
    def activate_user_by_token(self, token):
        user_activate_token = self.filter(
            token = token,
            expired_at__gte=datetime.now()
        ).first()
        user = user_activate_token.user
        user.is_active = True
        user.save()
        
class UserActivateTokens(models.Model):
    
    token = models.UUIDField(db_index=True)
    expired_at = models.DateTimeField()
    user = models.ForeignKey(
        'Users', on_delete=models.CASCADE
    )
    
    objects = UserActivateTokensManager()
    
    class Meta:
        db_table = 'user_activate_tokens'
        
# @receiver(post_save, sender=Users)
# def publish_token(sender, instance, **kwargs):
#     user_activate_token = UserActivateTokens.objects.create(
#         user = instance, token=str(uuid4()), expired_at = datetime.now() + timedelta(days=1)
#     )    
#     print(f'http://127.0.0.1:8000/accounts/activate_user/{user_activate_token.token}')

animal_community/accounts/forms.py
from typing import Any
from django import forms
from .models import Users, Pet
from django.contrib.auth.password_validation import validate_password


class RegistForm(forms.ModelForm):
    username = forms.CharField(label='名前')
    age = forms.IntegerField(label='年齢', min_value=0)
    email = forms.EmailField(label='メールアドレス')
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='パスワード再入力', widget=forms.PasswordInput())
    
    class Meta():
        model = Users
        fields = ('username','age','email','password')
        
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('パスワードが異なります')
        
        
    def save(self, commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'], user)
        user.set_password(self.cleaned_data['password'])
        user.is_active = True  # ユーザーをアクティブに設定
        if commit:
            user.save()
        return user    
        
class LoginForm(forms.Form):
    email = forms.CharField(label="メールアドレス")
    password = forms.CharField(label="パスワード", widget=forms.PasswordInput())
    
class UserEditForm(forms.ModelForm):
    username = forms.CharField(label='名前')
    age = forms.IntegerField(label='年齢', min_value=0)
    email = forms.EmailField(label='メールアドレス')
    bio = forms.CharField(
        label='自己紹介',
        widget=forms.Textarea(attrs={'rows': 4, 'cols': 40}),
        required=False,
    ) 
    favorite_animals  = forms.MultipleChoiceField(label='好きな動物',choices=(
        (1, '犬'),
        (2, '猫'),
        (3, '鳥'),
        (4, 'ウサギ'),
        (5, '爬虫類'),
    ), widget=forms.CheckboxSelectMultiple, required=False)
    picture = forms.ImageField(label='写真', required=False)  
    
    class Meta:
        model = Users
        fields = ('username','age','favorite_animals','email','bio','picture')
    
def clean_picture(self):
    picture = self.cleaned_data.get('picture')
    if self.cleaned_data.get('picture') is None and 'picture-clear' in self.data:
        return None
    return picture

class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label='新規パスワード', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='新規パスワード再入力', widget=forms.PasswordInput())
    
    class Meta():
        model = Users
        fields = ('password',)
        
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('パスワードが異なります')
        
        
    def save(self, commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'], user)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user     
    

class PetRegistForm(forms.ModelForm):
    name = forms.CharField(label='ペットの名前')
    age = forms.IntegerField(label='年齢', min_value=0)
    sex = forms.ChoiceField(label='性別', choices=(('1', 'オス'), ('2', 'メス')))
    picture = forms.ImageField(label='ペットの写真', required=False)
    genre = forms.ChoiceField(
        label='種類',
        choices=(
            ('1', '犬'),
            ('2', '猫'),
            ('3', '鳥類'),
            ('4', '齧歯類'),
            ('5', '爬虫類'),
        )
    )
    breed = forms.CharField(label='品種', required=False)  # 入力は不必要
    characteristic = forms.CharField(
        label='性格や特徴',
        widget=forms.Textarea(attrs={'rows': 3}),
        required=False  # 入力は不必要
    )

    class Meta:
        model = Pet
        fields = ('name', 'age', 'sex', 'genre', 'breed', 'characteristic', 'picture')


class DeletePetForm(forms.Form):
    confirm = forms.BooleanField(label='このペットを削除しますか？')

animal_community/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import forms
from django.core.exceptions import ValidationError
from .models import UserActivateTokens, Pet, Users
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.http import Http404

def home(request):
    return render(
        request, 'accounts/home.html'
    )
    
def regist(request):
    regist_form = forms.RegistForm(request.POST or None)
    if regist_form.is_valid():
        try:
            user = regist_form.save(commit=False)
            user.is_active = True  # ユーザーをアクティブに設定
            user.save()
            return redirect('accounts:home')
        except ValidationError as e:
            regist_form.add_error('password', e) 
    return render(
        request, 'accounts/regist.html', context={
            'regist_form': regist_form,
        }
    )
    
def activate_user(request, token):
    user_activate_token = UserActivateTokens.objects.activate_user_by_token(token)
    return render(
        request, 'accounts/activate_user.html'
    )
    
def user_login(request):
    login_form = forms.LoginForm(request.POST or None)
    if login_form.is_valid():
        email = login_form.cleaned_data.get('email')
        password = login_form.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        if user:
            if user.is_active:
                login(request, user)
                messages.success(request, 'ログイン完了しました')
                return redirect('accounts:home')
            else:
                messages.warning(request, 'ユーザーがアクティブではありません')
        else:
            messages.warning(request, 'ユーザーかパスワードが間違っています')
    return render(
        request, 'accounts/user_login.html',context={
            'login_form': login_form,
        }
    )
            
@login_required
def user_logout(request):
    logout(request)
    messages.success(request, 'ログアウトしました')
    return redirect('accounts:home')

@login_required
def user_edit(request):
    user_edit_form = forms.UserEditForm(request.POST or None, request.FILES or None, instance=request.user)
    if user_edit_form.is_valid():
        user = user_edit_form.save(commit=False)
        user.favorite_animals = ''.join(user_edit_form.cleaned_data['favorite_animals'])
        user.save()
        messages.success(request, '更新完了しました。')
        return redirect('accounts:user_profile', user_id=request.user.id)
    return render(
            request, 'accounts/user_edit.html', context={
            'user_edit_form': user_edit_form,
        }
    )
        
@login_required
def change_password(request):
    password_change_form = forms.PasswordChangeForm(request.POST or None, instance=request.user)
    if password_change_form.is_valid():
        try:
            password_change_form.save()
            messages.success(request, 'パスワードを変更しました')
            update_session_auth_hash(request, request.user)
        except ValidationError as e:
            password_change_form.add_error('password', e)
    return render(
        request, 'accounts/change_password.html', context={
            'password_change_form': password_change_form,
        }
    )


def show_error_page(request, exception):
    return render(
        request, '404.html'
    )
    
@login_required
def user_profile(request, user_id):
    user = get_object_or_404(Users, id=user_id)
    user_pets = user.pet.all()  # ログインユーザーのペット情報を取得
    return render(
        request, 'accounts/user_profile.html', context={
            'user': user,
            'user_pets': user_pets,  # ペット情報をテンプレートに渡す
        }
    )
    

@login_required
def pet_regist(request):
    pet_form = forms.PetRegistForm(request.POST or None, request.FILES or None)
    if pet_form.is_valid():
        pet = pet_form.save(commit=False)
        pet.owner = request.user
        if not pet.picture:
            pet.picture = 'pet_pictures/default_pet.jpg'
        pet.save()
        request.user.pet.add(pet)
        messages.success(request, 'ペット情報を登録しました。')
        return redirect('accounts:user_profile', user_id=request.user.id)

    user_pets = request.user.pet.all()
    
    return render(
        request, 'accounts/pet_regist.html', context={
            'pet_form': pet_form,
            'user_pets': user_pets,  # 取得したペット情報をテンプレートに渡す
        }
    )
    

@login_required
def pet_profile(request, pet_id):
    pet = Pet.objects.get(id=pet_id)
    return render(
        request, 'accounts/pet_profile.html', context={
            'pet': pet,
        }
    )

@login_required
def delete_pet(request, pet_id):
    pet = get_object_or_404(Pet, id=pet_id)
    if pet not in request.user.pet.all():
        raise Http404

    delete_pet_form = forms.DeletePetForm(request.POST or None)
    
    if request.method == 'POST':
        if delete_pet_form.is_valid():
            if delete_pet_form.cleaned_data['confirm']:
                pet.delete()
                messages.success(request, f'{pet.name}のプロフィールを削除しました。')
                return redirect('accounts:user_profile', user_id=request.user.id)
            else:
                messages.error(request, '削除がキャンセルされました。')
    
    return render(
        request, 'accounts/delete_pet.html', context={
            'delete_pet_form': delete_pet_form,
            'pet': pet,
        }
    )
    
@login_required
def pet_edit(request, pet_id):
    pet = get_object_or_404(Pet, id=pet_id)

    # ログインユーザーがペットの所有者か確認
    if pet not in request.user.pet.all():
        raise Http404

    pet_form = forms.PetRegistForm(request.POST or None, request.FILES or None, instance=pet)
    
    if pet_form.is_valid():
        pet_form.save()
        messages.success(request, f'{pet.name}の情報を更新しました。')
        return redirect('accounts:pet_profile', pet_id=pet.id)
    
    return render(
        request, 'accounts/pet_edit.html', context={
            'pet_form': pet_form,
            'pet': pet,
        }
    )

animal_community/templates/accounts/activate_user.html
{% extends "base.html" %}
{% block content %}
ユーザーを有効化しました
{% endblock %}

animal_community/templates/accounts/change_password.html
{% extends "base.html" %}
{% block content %}

<center>
{% if messages %}
    {% for message in messages %}
        <div>{{ message.message }}</div>
    {% endfor %}
{% endif %}
</center>
<form method="POST">
<center>
        <h1>プロフィール変更</h1>
    <table>
        {% csrf_token %}
        {{ password_change_form.as_table }}
    </table>
    <input type="submit" value="パスワード更新">
</center>
</form>
{% endblock %}

animal_community/templates/accounts/delete_pet.html
{% extends "base.html" %}

{% block content %}
<h1>{{ pet.name }}の削除確認</h1>
<p>本当にこのペット情報を削除しますか？</p>
<form method="post">
    {% csrf_token %}
    {{ delete_pet_form.as_p }}
    <button type="submit">削除する</button>
    <a href="{% url 'accounts:user_profile' user_id=user.id %}">キャンセル</a>
</form>
{% endblock %}

animal_community/templates/accounts/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var fadeInElements = document.querySelectorAll('.fade-in');
            
            fadeInElements.forEach(function(element) {
                element.classList.add('show');
            });

            // アラートの処理
            var alerts = document.querySelectorAll('.alert');
            alerts.forEach(function(alert) {
                alert.addEventListener('animationend', function() {
                    alert.style.display = 'none'; // アニメーションが終了した後にメッセージを非表示にする
                });
            });
        });
    </script>
</head>
<div class="home-container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-info">{{ message.message }}</div>
        {% endfor %}
    {% endif %}
    <div class="home-content">
        <div class="fade-in fade-in-left">
            <h1 class="home-title">ホーム</h1>
            <p class="home-subtitle">動物好きのためのSNS<br>「ぺっとも！」</p>
        </div>
        {% if not user.is_authenticated %}
            <div class="home-buttons">
                <a href="{% url 'accounts:regist' %}" class="btn btn-outline-success">新規登録</a>
                <a href="{% url 'accounts:user_login' %}" class="btn btn-outline-primary">ログイン</a>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

animal_community/templates/accounts/pet_edit.html
{% extends 'base.html' %}

{% block content %}
  <h2>{{ pet.name }}の情報を編集</h2>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ pet_form.as_p }}
    <button type="submit" class="btn btn-primary">更新</button>
  </form>
  <a href="{% url 'accounts:pet_profile' pet.id %}">戻る</a>
{% endblock %}

animal_community/templates/accounts/pet_profile.html
{% extends "base.html" %}
{% block content %}
<center>
<h1>{{ pet.name }}のプロフィール</h1>
<img width="400px" height="400px" src="{% if pet.picture %}{{ pet.picture.url }}{% else %}/media/pet_pictures/default_pet.jpg{% endif %}">
<p>名前: {{ pet.name }}</p>
<p>年齢: {{ pet.age }}歳</p>
<p>性別: {{ pet.get_sex_display }}</p>
<p>種類: {{ pet.get_genre_display }}</p>
<p>品種: {{ pet.breed }}</p>
<p>性格や特徴: {{ pet.characteristic }}</p>

{% if user.id == pet.owner.id %}
    <form method="post" action="{% url 'accounts:delete_pet' pet.id %}">
        {% csrf_token %}
        <a href="{% url 'accounts:pet_edit' pet.id %}" class="btn btn-outline-primary">編集</a>
        <button type="submit" class="btn btn-outline-danger">このペットの情報を削除</button>
    </form>
{% else %}
    <!-- 所有者でない場合はボタンを表示しない -->
{% endif %}
<a href="{% url 'accounts:user_profile' user_id=pet.owner.id %}" class="btn btn-outline-secondary mt-2">戻る</a>
</center>
{% endblock %}

animal_community/templates/accounts/pet_regist.html
{% extends 'base.html' %}

{% block content %}
<center>
    {% if messages %}
        {% for message in messages %}
            <div>{{ message.message }}</div>
        {% endfor %}
    {% endif %}
    <h2>ペット情報の登録</h2>
    <form method="POST" enctype="multipart/form-data">
        <table>
        {% csrf_token %}
        {{ pet_form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">登録</button>
    </form>
<hr>
<h3>既に登録されているペット情報</h3>
    {% if user_pets %}
        <ul>
            {% for pet in user_pets %}
                <li type="none">
                        <img width="100px" height="100px" src="{% if pet.picture %}{{ pet.picture.url }}{% else %}/media/pet_pictures/default_pet.jpg{% endif %}"><br>
                        {{ pet.name }} <br>
                        ({{ pet.get_genre_display }}, {{ pet.get_sex_display }})<br>
                    <a href="{% url 'accounts:pet_profile' pet.id %}" class="btn btn-outline-success">プロフィール</a>
                    <a href="{% url 'accounts:pet_edit' pet.id %}" class="btn btn-outline-primary">編集</a>
                    <a href="{% url 'accounts:delete_pet' pet.id %}" class="btn btn-outline-danger">削除</a>
                    <hr>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>ペットが登録されていません。</p>
    {% endif %}
</center>
{% endblock %}

animal_community/templates/accounts/regist.html
{% extends "base.html" %}
{% block content %}
<center>
    <strong>
    <h1>新規登録</h1>
    </strong>
    <form method="POST">
        <table>
        {% csrf_token %}
        {{ regist_form.as_table }}
        </table>
        <input type="submit" value="ユーザー登録">
    </form>
</center>
{% endblock %}

animal_community/templates/accounts/user_edit.html
{% extends "base.html" %}
{% block content %}

<center>
{% if messages %}
    {% for message in messages %}
        <div>{{ message.message }}</div>
    {% endfor %}
{% endif %}
<form method="POST" enctype="multipart/form-data">
        <h1>プロフィール変更</h1>
    <table>
        {% csrf_token %}
        {{ user_edit_form.as_table }}
    </table>
    <input type="submit" value="更新">
</form>
<a href="{% url 'accounts:change_password' %}">パスワード変更</a>
</center>
{% endblock %}

animal_community/templates/accounts/user_login.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
{% for message in messages %}
    <div class="text-center" >{{ message.message }}</div>
{% endfor %}
{% endif %}
<div class="login-container">
    <h1 class="text-center mb-3">ログイン画面</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="form-floating mb-3 col-6 mx-auto">
            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" name="email">
            <label for="floatingInput">メールアドレス</label>
        </div>
        <div class="form-floating mb-3 col-6 mx-auto">
            <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
            <label for="floatingPassword">パスワード</label>
        </div>
        <div class="d-grid gap-2 col-6 mx-auto">
            <button class="btn btn-primary" type="submit">ログイン</button>
        </div>
    </form>
</div>
{% endblock %}

animal_community/templates/accounts/user_profile.html
{% extends "base.html" %}
{% block content %}
<!DOCTYPE html>
<html>
<center>
    {% if messages %}
        {% for message in messages %}
            <div>{{ message.message }}</div>
        {% endfor %}
    {% endif %}
    {% if user.id == request.user.id %}
    <p><a class="navbar-brand" href="{% url 'accounts:user_edit' %}">プロフィールの変更</a></p>
    {% else %}
    {% endif %}
<head>
    <title>プロフィール</title>
</head>
<body>
    <h1>{{ user.username }}のプロフィール</h1>
    <img width="200px" height="200px" src="{% if user.picture %}{{ user.picture.url }}{% else %}/media/picture/default_profile.jpg{% endif %}">
    <p><strong>名前:</strong> {{ user.username }}</p>
    <p><strong>年齢:</strong> {{ user.age }}</p>
    <p><strong>好きな動物:</strong>
        {% if user.favorite_animals %}
            {% for animal in user.favorite_animals %}
                {% if animal == '1' %} 🐶 犬
                {% elif animal == '2' %} 🐱 猫
                {% elif animal == '3' %} 🐦 鳥
                {% elif animal == '4' %} 🐰 ウサギ
                {% elif animal == '5' %} 🦎 爬虫類
                {% endif %}
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        {% else %}
            なし
        {% endif %}
    </p>
    <p><strong>自己紹介:</strong> {{ user.bio }}</p>
    <p><strong>メールアドレス:</strong> {{ user.email }}</p>
    <h2>{{ user.username }}さんのペット情報</h2>
    {% if user_pets %}
        <ul>
            {% for pet in user_pets %}
                <a href="{% url 'accounts:pet_profile' pet.id %}">
                    {{ pet.name }}({{ pet.get_sex_display }})<br>
                </a>
            {% endfor %}
        </ul>
    {% else %}
        <p>ペットが登録されていません。</p>
    {% endif %}
</body>
</center>
</html>
{% endblock %}