animal_community/accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static  


app_name = 'accounts'

urlpatterns = [
    path('',views.home, name='home'),
    path('regist', views.regist, name='regist'),
    path('activate_user/<uuid:token>',views.activate_user, name='activate_user'),
    path('user_login', views.user_login, name='user_login'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('user_edit', views.user_edit, name='user_edit'),
    path('user_profile/<int:user_id>', views.user_profile, name='user_profile'),
    path('change_password', views.change_password, name='change_password'),
    path('pet_regist/', views.pet_regist, name='pet_regist'),
    path('profile/pet/<int:pet_id>/', views.pet_profile, name='pet_profile'),
    path('delete_pet/<int:pet_id>', views.delete_pet, name='delete_pet'),
    path('pets/<int:pet_id>/edit/', views.pet_edit, name='pet_edit'),  # ペット編集へのリンク
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

animal_community/animal_community/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import show_error_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('chat_category/', include('chat_category.urls')),
]

handler404 = show_error_page

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

animal_community/chat_category/urls.py
from django.urls import path
from . import views

app_name = 'chat_category'

urlpatterns = [
    path('create_theme', views.create_theme, name='create_theme'),
    path('list_themes', views.list_themes, name='list_themes'),
    path('edit_theme/<int:id>', views.edit_theme, name='edit_theme'),
    path('delete_theme/<int:id>', views.delete_theme, name='delete_theme'),
    path('post_comments/<int:theme_id>', views.post_comments, name='post_comments'),
    path('post_delete/<int:id>', views.post_delete, name='post_delete'),
    path('save_comment', views.save_comment, name='save_comment'),
    path('like_comment/<int:comment_id>/', views.like_comment, name='like_comment'),
]

animal_community/chat_category/models.py
from django.db import models

class ThemesManager(models.Manager):
    
    def fetch_all_themes(self):
        return self.order_by('id').all()


class Themes(models.Model):
    PET_GENRE_CHOICES = (
        (1, '犬'),
        (2, '猫'),
        (3, '鳥'),
        (4, 'ウサギ'),
        (5, '爬虫類'),
    )
    
    title = models.CharField(max_length=255)
    pet_genre = models.IntegerField(choices=PET_GENRE_CHOICES, default=1)
    user = models.ForeignKey(
        'accounts.Users', on_delete=models.CASCADE
    )
    
    objects = ThemesManager()
    
    class Meta:
        db_table = 'themes'

class CommentsManager(models.Manager):
    def fetch_by_theme_id(self, theme_id):
        return self.filter(theme_id=theme_id).order_by('id').all()
             

class Comments(models.Model):
    
    comment = models.CharField(max_length=1000)
    user = models.ForeignKey(
        'accounts.Users', on_delete=models.CASCADE
    )
    theme = models.ForeignKey(
        'Themes', on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to='comments_images/', blank=True, null=True)
    objects = CommentsManager()
    
    def like_count(self):
        return self.likes.count()  # 「いいね」の数を取得

    class Meta:
        db_table = 'comments'

class Like(models.Model):
    comment = models.ForeignKey(
        Comments, related_name='likes', on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        'accounts.Users', on_delete=models.CASCADE
    )
    
    class Meta:
        unique_together = ('comment', 'user')  # ユーザーが同じコメントに複数回「いいね」できないようにする
        db_table = 'likes'

animal_community/chat_category/forms.py
from django import forms
from .models import Themes, Comments


class CreateThemeForm(forms.ModelForm):
    title = forms.CharField(label='タイトル')
    pet_genre = forms.ChoiceField(label='ペットジャンル', choices=(
        (1, '犬'),
        (2, '猫'),
        (3, '鳥'),
        (4, 'ウサギ'),
        (5, '爬虫類'),
    ), widget=forms.RadioSelect)
    
    class Meta:
        model = Themes
        fields = ('title','pet_genre',)
    

class DeleteThemeForm(forms.ModelForm):
    
    class Meta:
        model = Themes
        fields = []
        

class PostCommentsForm(forms.ModelForm):
    comment = forms.CharField(label='',widget=forms.Textarea(attrs={'rows': 5, 'cols': 60}))
    image = forms.ImageField(required=False, label='画像')
    
    class Meta:
        model = Comments
        fields = ('comment', 'image')
        
class DeletePostForm(forms.ModelForm):
    
    class Meta:
        model = Comments
        fields = []

animal_community/chat_category/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import forms
from django.contrib import messages
from .models import Themes, Comments, Like
from django.http import Http404
from django.core.cache import cache
from django.http import JsonResponse


def create_theme(request):
    create_theme_form = forms.CreateThemeForm(request.POST or None)
    if create_theme_form.is_valid():
        create_theme_form.instance.user = request.user
        create_theme_form.save()
        messages.success(request, 'チャットカテゴリーを作成しました')
        return redirect('chat_category:list_themes')
        
    return render(
        request, 'chat_category/create_theme.html',context={
            'create_theme_form': create_theme_form,
        }
    )
    

def list_themes(request):
    themes = Themes.objects.fetch_all_themes()
    return render(
        request, 'chat_category/list_themes.html', context={
            'themes': themes
        }
    )
    
def edit_theme(request, id):
    theme = get_object_or_404(Themes, id=id)
    if theme.user.id != request.user.id:
        raise Http404
    edit_theme_form = forms.CreateThemeForm(request.POST or None, instance=theme)    
    if edit_theme_form.is_valid():
        edit_theme_form.save()
        messages.success(request, 'グループチャットを更新しました')
        return redirect('chat_category:list_themes')
    return render(
        request, 'chat_category/edit_theme.html', context={
            'edit_theme_form': edit_theme_form,
            'id': id,
        }
    )
    

def delete_theme(request, id):
    theme = get_object_or_404(Themes, id=id)
    if theme.user.id != request.user.id:
        raise Http404
    delete_theme_form = forms.DeleteThemeForm(request.POST or None)
    if delete_theme_form.is_valid():
        theme.delete()
        messages.success(request, 'グループチャットを削除しました')
        return redirect('chat_category:list_themes')
    return render(
        request, 'chat_category/delete_theme.html',context={
            'delete_theme_form': delete_theme_form, 
        }
    )
    

def post_comments(request, theme_id):
    # `theme`を最初に取得
    theme = get_object_or_404(Themes, id=theme_id)  # 追加

    saved_comment = cache.get(f'saved_comment-theme_id={theme_id}-user_id={request.user.id}', '')
    
    if request.method == 'POST':  # POSTメソッドであるかを確認
        post_comments_form = forms.PostCommentsForm(request.POST, request.FILES, initial={'comment': saved_comment})  # request.FILESを追加
        if post_comments_form.is_valid():
            if not request.user.is_authenticated:
                raise Http404
            post_comments_form.instance.theme = theme
            post_comments_form.instance.user = request.user
            post_comments_form.save()
            cache.delete(f'saved_comment-theme_id={theme_id}-user_id={request.user.id}')
            return redirect('chat_category:post_comments', theme_id=theme_id)
    else:
        post_comments_form = forms.PostCommentsForm(initial={'comment': saved_comment})

    comments = Comments.objects.fetch_by_theme_id(theme_id)
    return render(
        request, 'chat_category/post_comments.html', context={
            'post_comments_form': post_comments_form,
            'theme': theme,
            'comments': comments,
        }
    )
    
def post_delete(request, id):
    post = get_object_or_404(Comments, id=id)
    if post.user.id != request.user.id:
        raise Http404
    delete_post_form = forms.DeletePostForm(request.POST or None)
    if delete_post_form.is_valid():
        post.delete()
        messages.success(request, '投稿を削除しました')
        return redirect('chat_category:post_comments', theme_id=post.theme.id)
    return render(
        request, 'chat_category/post_delete.html',context={
            'delete_post_form': delete_post_form, 
        }
    )

def save_comment(request):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        comment = request.GET.get('comment')
        theme_id = request.GET.get('theme_id')
        if comment and theme_id:
            cache.set(f'saved_comment-theme_id={theme_id}-user_id={request.user.id}', comment)
            return  JsonResponse({'message': '一時保存しました。'})
        
def like_comment(request, comment_id):
    comment = get_object_or_404(Comments, id=comment_id)
    user = request.user
    like, created = Like.objects.get_or_create(comment=comment, user=user)
    
    if not created:
        like.delete()  # 既に「いいね」している場合は取り消す
    
    return redirect('chat_category:post_comments', theme_id=comment.theme.id)

animal_community/templates/chat_category/create_theme.html
{% extends "base.html" %}
{% block content %}
<center>
    <strong>
    <h1>グループチャット作成画面</h1>
    </strong>
    <form method="POST">
        <table>
        {% csrf_token %}
        {{ create_theme_form.as_table }}
        </table>
        <input type="submit" value="グループチャット作成">
    </form>
</center>
{% endblock %}

animal_community/templates/chat_category/delete_theme.html
{% extends "base.html" %}
{% block content %}
<center>
    <strong>
    <h1>グループチャット削除画面</h1>
    </strong>
    <form method="POST">
        <table>
        {% csrf_token %}
        {{ delete_theme_form.as_table }}
        </table>
        <input type="submit" value="削除">
    </form>
</center>
{% endblock %}

animal_community/templates/chat_category/edit_theme.html
{% extends "base.html" %}
{% block content %}
<center>
    <strong>
    <h1>グループチャット編集画面</h1>
    </strong>
    <form method="POST">
        <table>
        {% csrf_token %}
        {{ edit_theme_form.as_table }}
        </table>
        <input type="submit" value="更新">
    </form>
    <p><a class="navbar-brand" href="{% url 'chat_category:delete_theme' id=id %}">削除する</a></p>
</center>
{% endblock %}

animal_community/templates/chat_category/list_themes.html
{% extends "base.html" %}
{% block content %}
<center>
    {% if messages %}
        {% for message in messages %}
        <div>{{ message.message }}</div>
        {% endfor %}
    {% endif %}
    <strong>
    <h1>チャットカテゴリー</h1>
    </strong>
    {% if user.is_authenticated %}
        <p><a class="navbar-brand" href="{% url 'chat_category:create_theme'%}">グループチャット作成</a></p>
    {% endif %}
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>タイトル</th>
                <th>ペットジャンル</th>
                <th>作成者</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for theme in themes %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'chat_category:post_comments' theme_id=theme.id %}">{{theme.title }}</a></td>
                <td><a>{{ theme.get_pet_genre_display }}</a></td>
                <td>{{ theme.user.username }}</td>
                {% if theme.user.id == user.id %}
                    <td><a href="{% url 'chat_category:edit_theme' id=theme.id %}">編集</a></td>
                {% else %}
                    <td></td> <!-- 編集リンクが表示されない場合の空のセル -->
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</center>
{% endblock %}

animal_community/templates/chat_category/post_comments.html
{% extends "base.html" %}
{% block content %}
<center>
    {% if messages %}
        {% for message in messages %}
            <div>{{ message.message }}</div>
        {% endfor %}
    {% endif %}
    <h1>{{ theme.title }}</h1>
    {% if user.is_authenticated %}
    <form method="POST" enctype="multipart/form-data">
        <table>
        {% csrf_token %}
        {{ post_comments_form.as_table }}
        </table>
        <input type="button" value="一時保存" id="save_comment">
        <input type="submit" value="コメント送信">
    </form>
    {% else %}
    <p>コメントをしたい場合はログインをしてください。</p>
    {% endif %}
    <hr size="5">
</center>
    {% for comment in comments %}
    <div class="col-1 offset-1">
        {% if comment.user.picture %}
            <img style="float:left;" width="100px" height="100px" src="{{ comment.user.picture.url }}">
        {% endif %}
    </div>
    <div class="col-8 offset-2">
        <div style="display: flex; justify-content: space-between; align-items: center;">
            <strong><a href="{% url 'accounts:user_profile' user_id=comment.user.id %}"><p>{{ comment.user.username }}</p></a></strong>
            {% if comment.user == user %}
            <p><a class="navbar-brand" href="{% url 'chat_category:post_delete' id=comment.id %}">削除</a></p>
            {% endif %}
        </div>
        <p>{{ comment.comment | linebreaks }}</p>
        {% if comment.image %}
        <div>
            <img src="{{ comment.image.url }}" alt="Comment Image" style="max-width: 100%; height: auto;">
        </div>
        {% endif %}
        {% if user.is_authenticated %}
        <div>
            <a href="{% url 'chat_category:like_comment' comment.id %}">
                💗 {{ comment.like_count }} 
            </a>
        </div>
        {% endif %}
    </div>
    <div class="col-10 offset-1">
    <hr>
    </div>
    {% endfor %}
{% endblock %}
{% block javascript %}
<script>
    $("#save_comment").click(function(){
        var comment = $("#id_comment").val();
        $.ajax({
            url: "{% url 'chat_category:save_comment' %}",
            type: "GET",
            data: {comment: comment, theme_id: "{{ theme.id }}"},
            dataType: "json",
            success: function(json){
                if(json.message){
                    alert(json.message);
                }
            }
        });
    });
</script>
{% endblock %}

animal_community/templates/chat_category/post_delete.html
{% extends "base.html" %}
{% block content %}
<center>
    <strong>
    <h1>投稿削除画面</h1>
    </strong>
    <form method="POST">
        {% csrf_token %}
        {{ delete_post_form }}
        <input type="submit" value="削除">
    </form>
</center>
{% endblock %}