animal_community/accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static  


app_name = 'accounts'

urlpatterns = [
    path('',views.home, name='home'),
    path('regist', views.regist, name='regist'),
    path('activate_user/<uuid:token>',views.activate_user, name='activate_user'),
    path('user_login', views.user_login, name='user_login'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('user_edit', views.user_edit, name='user_edit'),
    path('user_profile/<int:user_id>', views.user_profile, name='user_profile'),
    path('change_password', views.change_password, name='change_password'),
    path('pet_regist/', views.pet_regist, name='pet_regist'),
    path('profile/pet/<int:pet_id>/', views.pet_profile, name='pet_profile'),
    path('delete_pet/<int:pet_id>', views.delete_pet, name='delete_pet'),
    path('pets/<int:pet_id>/edit/', views.pet_edit, name='pet_edit'),  # ペット編集へのリンク
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

animal_community/animal_community/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import show_error_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('chat_category/', include('chat_category.urls')),
]

handler404 = show_error_page

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

animal_community/chat_category/urls.py
from django.urls import path
from . import views

app_name = 'chat_category'

urlpatterns = [
    path('create_theme', views.create_theme, name='create_theme'),
    path('list_themes', views.list_themes, name='list_themes'),
    path('edit_theme/<int:id>', views.edit_theme, name='edit_theme'),
    path('delete_theme/<int:id>', views.delete_theme, name='delete_theme'),
    path('post_comments/<int:theme_id>', views.post_comments, name='post_comments'),
    path('post_delete/<int:id>', views.post_delete, name='post_delete'),
    path('save_comment', views.save_comment, name='save_comment'),
    path('like_comment/<int:comment_id>/', views.like_comment, name='like_comment'),
]

animal_community/templates/_footer.html
<div>
    <center>
        <footer>
            <p>お問い合わせ: info@example.com</p>
            <p>Copyright 2017-{% now "Y"%}</p>
        </footer>
    </center>
</div>

animal_community/templates/base.html
<!DOCTYPE html>
<html lang="ja">
    <title>ぺっとも！</title>
    <head>
        <meta charset="utf-8">
        <!-- bootstrap-->
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
         <script
         src="https://code.jquery.com/jquery-3.7.1.js"
         integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
         crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-dark border-bottom" >
            <a class="navbar-brand" style="color: white;" href="{% url 'accounts:home' %}">ホーム画面</a>
            <a class="navbar-brand" style="color: white;" href="{% url 'chat_category:list_themes'%}">チャットカテゴリー</a>
            {% if user.is_authenticated %}
            <a class="navbar-brand" style="color: white;" href="{% url 'accounts:user_profile' user_id=request.user.id %}">プロフィール</a>
            <a class="navbar-brand" style="color: white;" href="{% url 'accounts:pet_regist' %}">ペット情報登録</a>
            <a class="navbar-brand" style="color: white;" href="{% url 'accounts:user_logout'%}">ログアウト</a>
            {% else %}
            <a class="navbar-brand" style="color: white;" href="{% url 'accounts:user_login'%}">ログイン</a>
            <a class="navbar-brand" style="color: white;" href="{% url 'accounts:regist'%}">ユーザー登録</a>
            {% endif %}
        </nav>
    {% block content %}
    {% endblock %}
    {% block javascript %}
    {% endblock %}
    {% include "_footer.html"%}
    </body>
</html>

animal_community/templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>ぺっとも！</title>
    <link rel="stylesheet" href="{% static 'css/base2.css' %}" />
</head>

<body>
    <div class="container">
        <div class="navigation">
            <ul>
                <li class="list active">
                    <a href="{% url 'accounts:home' %}">
                        <span class="icon"><ion-icon name="home-outline"></ion-icon></span>
                        <span class="title">ホーム</span>
                    </a>
                </li>
                <li class="list">
                    <a href="{% url 'chat_category:list_themes'%}">
                        <span class="icon"><ion-icon name="chatbox-outline"></ion-icon></span>
                        <span class="title">チャットカテゴリー</span>
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li class="list">
                    <a href="{% url 'accounts:user_profile'%}">
                        <span class="icon"><ion-icon name="person-circle-outline"></ion-icon></span>
                        <span class="title">プロフィール</span>
                    </a>
                </li>
                <li class="list">
                    <a href="{% url 'accounts:pet_regist' %}">
                        <span class="icon"><ion-icon name="paw-outline"></ion-icon></span>
                        <span class="title">ペット情報の登録</span>
                    </a>
                </li>
                <li class="list">
                    <a href="{% url 'accounts:user_logout'%}">
                        <span class="icon"><ion-icon name="log-out-outline"></ion-icon></span>
                        <span class="title">サインアウト</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="content"> 
            {% block content %}
            {% endblock %}
        </div>
    </div>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script>
        const list = document.querySelectorAll(".list");
        function activeLink() {
            list.forEach((item) => item.classList.remove("active"));
            this.classList.add("active");
        }
        list.forEach((item) => {
            item.addEventListener("click", activeLink);
        });
    </script>
</body>
</html>